name: SSH Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run Deploy Script on Remote
        run: | 
          echo "${{ secrets.DEPLOY_KEY }}" > id_rsa
          chmod 600 id_rsa
          ssh -i id_rsa ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "${{ secrets.DEPLOY_COMMAND }}"
