name: SSH Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Add Known Host
        run: |
            mkdir -p /home/runner/.ssh
            ssh-keyscan ${{ secrets.DEPLOY_HOST }} >> /home/runner/.ssh/known_hosts

      - name: Call Remote Deploy Script
        run: | 
          echo "${{ secrets.DEPLOY_KEY }}" > id_rsa
          chmod 600 id_rsa
          ssh -i id_rsa ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "./deploy.sh"
